name: Build
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install project
        run: |
          poetry install --no-interaction
          cp -rv "$(python3 -c 'import importlib.metadata; print(importlib.metadata.distribution("spritoglobin_dx")._path)')" "spritoglobin_dx.dist-info"  # Workaround for https://github.com/Nuitka/Nuitka/issues/2965
      - name: Build executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: spritoglobin_dx
          mode: app
          enable-plugins: pyside6
          user-package-configuration-file: "spritoglobin_dx.nuitka-package.config.yml"
          windows-console-mode: attach
          windows-icon-from-ico: "spritoglobin_dx/files/ico_sprito_dx.ico"
          include-data-dir: "spritoglobin_dx.dist-info=spritoglobin_dx.dist-info"  # Workaround for https://github.com/Nuitka/Nuitka/issues/2965
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
